### PR TITLE
https://github.com/CPE-OAuth/servicestage-eclipse-plugin/issues/15

### PR DESCRIPTION
**Pull request by ewcchan**
- Add new IAM fields in preference page
- Add Test Connection button in preference page, along with result
dialog
- Apply user changes in preference store
- Add new resources for UI
- Update helper methods
- Update client jar with new authentication support.

@farhan3 @paulmchen please review and merge.

### CODE REVIEW

**Comment by paulmchen** [comment]
1. the eclipse UI had been changed to add "account" and "test connection" button, so the main readme.md on this project needs to be updated to include the latest screenshot as well. Please update it.  
2. I don't see the new jar was produced and checked in under the plugins/ folder, we would need to update it there
3. Since i don't have set up the compile env, to verify the run, i assume you have done with the end 2 end test with this against the ServiceStage. I would ask SS team to have a quick look at as well before we mrerget it in. Thanks!

**Comment by ewcchan** [comment]
@paulmchen Thanks for your feedback. I have update the code based on your https://github.com/CPE-OAuth/servicestage-eclipse-plugin/pull/16#issuecomment-467243546 and submitted  along the changes in this PR as a new PR https://github.com/CPE-OAuth/servicestage-eclipse-plugin/pull/17

**Comment by ewcchan** [comment]
Marking this close and re-submit as PR #17.

**Comment by ewcchan** [comment]
replaced by PR https://github.com/CPE-OAuth/servicestage-eclipse-plugin/pull/19

**Pull request closed without merging**
